some-fixes-in-flow

diff --git a/.github/actions/android/unsigned/action.yml b/.github/actions/android/unsigned/action.yml
--- a/.github/actions/android/unsigned/action.yml
+++ b/.github/actions/android/unsigned/action.yml
@@ -30,11 +30,15 @@ runs:
       shell: bash
       run: |
         flutter build apk --release --build-name ${{ inputs.VERSION_NAME }} --build-number ${{ inputs.VERSION_CODE }}
+        if [ ! -f build/app/outputs/flutter-apk/app-release.apk ]; then
+          echo "Unsigned APK not found. Build might have failed."
+          exit 1
+        fi
 
-    - name: Setup Git and Clone or Init Branch
+    - name: Clone or Init apk-unsigned Branch
       shell: bash
       run: |
-        git clone https://x-access-token:${{ inputs.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git apk-temp
+        git clone --depth=1 https://x-access-token:${{ inputs.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git apk-temp
         cd apk-temp
         if git ls-remote --exit-code --heads origin apk-unsigned; then
           git checkout apk-unsigned
@@ -57,5 +61,11 @@ runs:
         git config user.name "github-actions[bot]"
         git config user.email "github-actions[bot]@users.noreply.github.com"
         git add unsigned.apk
-        git commit -m "Update unsigned APK with version ${{ inputs.VERSION_NAME }} (${{ inputs.VERSION_CODE }})" || echo "Nothing to commit"
+        git commit -m "[Unsigned APK] Update for v${{ inputs.VERSION_NAME }} (#${{ inputs.VERSION_CODE }})" || echo "Nothing to commit"
         git push -u origin apk-unsigned
+
+    - name: Upload Unsigned APK as Artifact
+      uses: actions/upload-artifact@v4
+      with:
+        name: unsigned-apk
+        path: build/app/outputs/flutter-apk/app-release.apk
